name = "CLib"
mainprefix = "tc"
modname = "CLib"
prefix = ""
author = "CLib Team"
sig_version = 3
version = "0.0.0" # NB: this is not the real version number. We use git tags.
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE",
    "*.dll",
    "CLibDataBaseEditor.exe"
]
include = ["./include"]

releasebuild = [
    "@zip @CLib"
]

key_name = "CLib_{{version}}"
authority = "CLib_{{version}}-{{git \"id 8\"}}"

[header_exts]
version= "{{git \"id 8\"}}"
